default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: Junior_Project_development

test:
  <<: *default
  database: Junior_Project_test

production:
  <<: *default
  url: postgres://test:xci3iFOGQZuZuWs2rT3z8tfwVpZM62jC@dpg-cf00m4qrrk0eqcoqlm0g-a/test_81q8
  host: test
  database: test_81q8
  username: test
  password: xci3iFOGQZuZuWs2rT3z8tfwVpZM62jC