default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: Junior_Project_development

test:
  <<: *default
  database: Junior_Project_test

production:
  <<: *default
  url: postgres://root:iW13U8xtHBNv7xmthlT660Ie7NqdSGXg@dpg-cf26ig1gp3jl0q170010-a/juniors
  database: juniors_production
  username: root
  password: iW13U8xtHBNv7xmthlT660Ie7NqdSGXg