local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:secret_access_key) %>
  bucket: mybucket953
  region: "eu-central-1"
